# Generated by Django 4.1 on 2023-05-02 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("building", "0002_alter_pk_location_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pk_location",
            options={
                "verbose_name": "각 건물의 주차 공간",
                "verbose_name_plural": "각 건물의 주차 공간",
            },
        ),
    ]
